"project_identifier": "decentraleyes"
"preserve_hierarchy": true
"files":
  -
    "source": "/_locales/en_US/messages.json"
    "translation": "/_locales/%locale_with_underscore%/messages.json"
    "languages_mapping":
      "locale_with_underscore":
        "ar": "ar"
        "bg": "bg"
        "da": "da"
        "de": "de"
        "el": "el"
        "et": "et"
        "eo": "eo"
        "es-ES": "es"
        "fi": "fi"
        "fr": "fr"
        "he": "he"
        "hu": "hu"
        "id": "id"
        "is": "is"
        "it": "it"
        "ja": "ja"
        "ko": "ko"
        "nl": "nl"
        "pl": "pl"
        "ro": "ro"
        "ru": "ru"
        "sr": "sr"
        "sv-SE": "sv"
        "tr": "tr"
